apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.app}}
  namespace: {{.Values.namespace}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{.Values.app}}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{.Values.app}}
        repository: {{.Values.image.repository}}
    spec:
      containers:
        - name: {{.Values.app}}
          image: {{.Values.image.name}}:{{.Values.image.tag}}
          imagePullPolicy: {{.Values.image.pullPolicy}}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{.Values.application.config.profile}}
            - name: POSTGRES_URL
              value: {{.Values.application.config.database_url}}
            - name: POSTGRES_USER
              value: {{.Values.application.config.database_user}}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD

          ports:
            - containerPort: {{.Values.service.port}}

