apiVersion: v1
kind: Service
metadata:
  name: {{.Values.app}}
  namespace: {{.Values.namespace}}
  labels:
    app.kubernetes.io/name: {{.Values.app}}
spec:
  ports:
    - port: {{.Values.service.port}}
      targetPort: {{.Values.service.targetPort}}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{.Values.app}}
---
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: {{.Values.app}}
  namespace: {{.Values.namespace}}
spec:
  serviceRef:
    name: {{.Values.app}}
    port: {{.Values.service.port}}
  targetGroupARN: {{.Values.service.targetGroupARN}}
